### ISSUE TITLE
Strongly discourage use of the default keystore outside sandbox

### ISSUE THREAD

**Issue by chrisshiplet** [synapsestudios/oidc-platform#239] opened 2017-12-05 01:29 UTC
David ran into an interesting issue when upgrading a project’s OIDC installation up a major version. The issue was that the project shipped OIDC's default keystore in the repo and required it directly, but that keystore was regenerated as part of the 2.0.0 upgrade. He correctly followed the upgrade guide and modified the format of his existing keystore, but it throws a somewhat cryptic error about `no key found` when the `verifyJWT` function runs and passes it into `node-jose`. 

Figuring out that the keystore itself changed and needed to be copied over to the repo again took a fairly significant amount of time to pin down and it's a pain point I could see others having in the future with this configuration, so I think it's worthwhile to discuss how to be more proactive about this.

My opinion is that the default keystore should never be allowed outside of sandbox mode, and if you're using OIDC in your project, you should _always_ have to generate your own keystore and upload it to S3 for it to function correctly. This ensures that your API keystore and OIDC keystore are synced up and won't be affected by OIDC upgrades in the future.

If this is too hardline of a stance to take, I want to at least make it VERY clear to the user that they are using the default keystore when OIDC boots up, maybe logging a prominent warning message to the console.

Alternatively, maybe I'm wrong and using the default keystore in development/qa is a perfectly valid pattern. Either way, opening this for discussion. DISCUSS.

**Comment by chrisshiplet** [comment] 2017-12-05 01:34
#111 is potentially relevant here

**Comment by bobeagan** [comment] 2019-02-15 00:35
Duplicate of #270

**Closed** 2019-02-15 16:29 UTC
