### ISSUE TITLE
Update inviteUser to query using email_lower column instead of email column

### ISSUE THREAD

**Issue by jakedemian** [synapsestudios/oidc-platform#542] opened 2022-02-09 17:07 UTC
If a user creates an account with capital letters in their email (eg: Jake.Demian@example.com), and then they are later invited using a different combination of upper/lower case letters (eg: jake.demian@example.com), OIDC responds with 500 as it's not realizing the user already exists, and tries to insert an already created user, resulting in:

```
error: 220208/201916.887, [error] message: insert into "SIP_user" ("app_metadata", "email", "email_lower", "id", "password", "profile") values ($1, $2, $3, $4, $5, $6) returning "id" - duplicate key value violates unique constraint "sip_user_email_lower_unique", stack: error: duplicate key value violates unique constraint "sip_user_email_lower_unique"
    at Connection.parseE (/src/node_modules/pg/lib/connection.js:555:11)
    at Connection.parseMessage (/src/node_modules/pg/lib/connection.js:380:19)
    at Socket.<anonymous> (/src/node_modules/pg/lib/connection.js:120:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)
```

Updating [this block](https://github.com/synapsestudios/oidc-platform/blob/master/api/src/application/user/user-service.js#L59-L82) to query based on the `email_lower` column rather than the `email` column should resolve this issue.

**Comment by zpchavez** [comment] 2022-02-09 17:09
This is a duplicate of https://github.com/synapsestudios/oidc-platform/issues/499

**Closed** 2022-02-09 17:27 UTC
Labels: duplicate
